SELECT
R.CODCLI,  C.CLIENTE, C.CGCENT,   C.CODREDE, RD.DESCRICAO AS REDE,
C.CODPRACA, C.CODATV1,A.RAMO,     C.ENDERENT, C.NUMEROENT,
C.CEPENT,  C.BAIRROENT, 
C.MUNICENT,C.ESTENT,  C.TELENT,   C.BLOQUEIO, C.CODCOB AS FORMA_PG,
C.CODPLPAG,
C.DTBLOQ,C.DTULTCOMP,
R.CODUSUR AS CODRCA,   U.NOME AS VENDEDOR1,  U.CODSUPERVISOR AS CODSUPER1, 
 R.DTPROXVISITA AS VEND_DTVISITA,  R.DIASEMANA AS VEND_DIASEMANA,  R.PERIODICIDADE AS VEND_PERIO,  R.SEQUENCIA AS VEND_SEQUENCIA
 FROM
PCCLIENT C INNER JOIN PCROTACLI R  ON (C.CODCLI = R.CODCLI )
LEFT JOIN PCUSUARI U ON (R.CODUSUR = U.CODUSUR)
INNER JOIN      PCATIVI A  ON  (C.CODATV1  = A.CODATIV )
LEFT JOIN PCREDECLIENTE RD ON (C.CODREDE = RD.CODREDE)